### ISSUE TITLE
[REQ] Jpeg-XL support

### ISSUE THREAD

**Issue by drwankingstein** [pop-os/cosmic-bg#44]
Image-rs does not support jpegxl and will not support it https://github.com/image-rs/image/issues/1979 so to use JXL images for backgrounds cosmic-bg will need to implement jxl-oxide directly https://github.com/tirr-c/jxl-oxide

**Comment by Conan-Kudo** [comment]
In Fedora, we are considering and leaning toward using JPEG XL for our default background images going forward, and it would be great if there was a way for cosmic-bg to support JPEG XL as well, so that we don't need an alternative file format for COSMIC to be able to load it.

**Comment by Conan-Kudo** [comment]
There's also [jpegxl-rs](https://crates.io/crates/jpegxl-rs) which wraps libjxl as an option.

Alternatively, [glycin](https://crates.io/crates/glycin) is an option if you want to work with GdkTextures.

**Comment by decathorpe** [comment]
FTR, glycin doesn't only support GdkTextures, you should also be able to just get the raw bytes for the image out of it if you don't want to use any GLib based APIs.

For context, Fedora ships glycin will all loader backends enabled, which includes image-rs for most formats, an svg backend based on librsvg, a JPEG-XL backend based on jpegxl-rs / libjxl, and a HEIF/HEIC backend based on libheif-rs / libheif. Older versions of glycin used jxl-oxide, but it switched to jpegxl-rs a while ago, I'm not sure why.

It's what's used by the default image viewer in GNOME 45+ (loupe), and IIUC it will be used in more places in the future (i.e. drawing the wallpaper) - to replace gdk-pixbuf with a safer alternative (both primarily written in Rust *and* it's running the image decoding process in a SECCOMP sandbox).

Oh, and glycin provides a Rust API too in addition to the GObject bindings, so it might work for this use case, too, since it provides a unified image loading API over all its supported backends.

**Comment by Quackdoc** [comment]
If Image::DynamicImage support is needed for consideration jxl-oxide can be wired up fairly easily. IMO it would be prefered since aside from lcms which is just for more advanced colormanagement, it's entirely rust native. 

If it's something that needs to happen upstream for it to be accepted, Tirr has stated that it could be included in jxl-oxide, it's just that no one has done it since it's more on the simple side of things, but that can be done if needed.

There is also Jxl-rs which has spun back up with tirr and libjxl folk working together on it https://github.com/libjxl/jxl-rs I'm not sure what the state of that is, but it should perform better then jxl-oxide when it's done.

**Comment by mmstick** [comment]
We don't use GLib in COSMIC. I made a PR with jpegxl-rs.

**Comment by Quackdoc** [comment]
Is GPL even compatible with this project? I did a quick check and `clipboard-win, error-code, xxhash-rust` are licenced under BSL which iirc is a GPL violation isn't it? jpegxl-rs is GPL 3.0 or later

**Comment by Conan-Kudo** [comment]
The Boost license is a permissive license and can be incorporated into a GPL project.

**Comment by Quackdoc** [comment]
ah, I thought BSL was buisness source licence, didn't realize it was boost, my bad

**Comment by Conan-Kudo** [comment]
BUSL is the Business Source License, BSL is the Boost Source License

**Comment by Quackdoc** [comment]
I have a quick for using jxl-oxide instead of jpegxl-rs if a rust dependency would be preferred, it's a bit more code, but being rust native I personally prefer it since I have had issues with jpegxl-rs cross compilation in the past.

Link for it is here https://github.com/Quackdoc/cosmic-bg/commit/600d15279297e3ba4c2d9f86072fc2a41558d0a7

**Comment by mmstick** [comment]
@Quackdoc You could open a PR against my PR branch if it works well

**Comment by Quackdoc** [comment]
Made a PR.

Tested on 3 images

woag.jxl: https://files.catbox.moe/fsmdyy.jxl
jpegxl-rs is a bit faster on my PC, but not enough for me to notice. Image resolution is 7680x4320

windwaker-35x.jxl: https://files.catbox.moe/31lths.jxl
This image takes a very long time to decode with jxl-oxide, at a resolution of 23164x18480 it's unlikely that anybody will actually be setting this as their wallpaper, but jpegxl-rs is for sure way better here.

jpegxl-home.jxl: https://files.catbox.moe/f7185e.jxl
This is an HDR image (PQ) and show cases a clear win for jxl-oxide as jxl-oxide has implicit colormanagement to sRGB advanced colormanagement can be enabled by compiling "jxl-oxide/lcms" which does rely on the C library lcms2.

I wouldn't say jxl-oxide is a clear winner or a looser. On one hand, jpegxl-rs does have better performance which could be a factor on low end PCs, on the other hand jxl-oxide will "look better" on a lot of images, which is becomming more important since phones are now starting to default to HDR.

I can push a commit which will make swapping between the two a compile time configuration if testing finds jxl-oxide to be too slow, but on my celeron N3050 machine with "reasonable resolutions" I have no such issue.

**Comment by tirr-c** [comment]
For clarity, jpegxl-home.jxl image above would not need `lcms2` feature -- jxl-oxide can do color management to some extent even without lcms2. It's only needed when the colorspace involves ICC profiles (which jxl-oxide will still try to parse and convert as much as possible without lcms2). Though I'd suggest turning the feature on for maximum compatibility, since image with uncommon (read: unrecognized by jxl-oxide) ICC profile does exist.
